name: 'actions'

on:
  push:
    tags:
      - '*'
  # schedule:
    # 北京时间 8点半，每月15执行
    # - cron: '30 0 15 * *'
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      # action命令，切换分支获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v2.4.0

      # action命令，安装Node.js
      - name: use Node.js
        # 使用github actions市场的开源库  actions/setup-node安装node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '14'

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8.0.312+7'

      - name: print
        run: java -version && node -v && npm -v && pwd && ls

      - name: build
        run: |
          export ORG_GRADLE_PROJECT_cdvBuildToolsVersion=30.0.3
          echo print-env
          echo ORG_GRADLE_PROJECT_cdvBuildToolsVersion
          echo "$ORG_GRADLE_PROJECT_cdvBuildToolsVersion"

          npm install -g cordova@8.1.0
          cordova -v
          cordova platform rm android
          cordova platform add android@8.1.0
          npm install
          cordova build android

      # 发布到github release
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "platforms/**/**.apk"
          token: ${{ secrets.HUB_TOKEN }}
